# Generated by Django 6.0.7 on 2026-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='business_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
