# Generated by Django 6.0.7 on 2026-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_ownerprofile_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='business_hours',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
