# Generated by Django 6.0.7 on 2026-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_ownerprofile_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='about_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='contact_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='feedback_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='home_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='medicines_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='services_image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site_images'),
        ),
    ]
