# Generated by Django 6.0.7 on 2026-08-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_ownerprofile_about_hero_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='about_image',
            new_name='about_page_image',
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='medicines_image',
            new_name='contact_page_image',
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='contact_image',
            new_name='feedback_page_image',
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='feedback_image',
            new_name='medicines_page_image',
        ),
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='services_image',
            new_name='services_page_image',
        ),
    ]
