# Generated by Django 6.0.7 on 2026-08-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_about_image_ownerprofile_about_page_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='about_hero_image',
            new_name='home_about_image',
        ),
    ]
