# Generated by Django 6.0.7 on 2026-08-09 14:56

import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_about_hero_image_ownerprofile_home_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='home_hero_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
    ]
