# Generated by Django 6.0.7 on 2026-08-09 15:13

import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_ownerprofile_home_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='about_page_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='contact_page_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='feedback_page_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='home_about_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='medicines_page_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='services_page_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='public_site_images'),
        ),
    ]
