# Generated by Django 6.0.7 on 2026-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_ownerprofile_about_page_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
