# Generated by Django 6.0.7 on 2026-08-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_backupfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupFile',
        ),
    ]
