# Generated by Django 6.0.7 on 2026-08-11 15:30

import website.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_delete_backupfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, storage=website.storage.ImageKitStorage, upload_to='medicine_images/'),
        ),
    ]
